apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crudapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: coffeshop
  containers:
    - name: crudapplication
      image: docker.io/umesh1809/crudapp
      ports:
        - containerPort: 32777
