apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp  # Also fixed label to match selector
    spec:
      containers:
        - name: crudapplication
          image: docker.io/umesh1809/crudapp
          ports:
            - containerPort: 32778
          imagePullSecrets:
            - name: regcred
