apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: crudapplication
          image: docker.io/umesh1809/crudapp:1.0.1
          ports:
            - containerPort: 32778
