apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coffeshop
  template:
    metadata:
      labels:
        app: coffeshop
    spec:
      containers:
        - name: crudapplication
          image: umesh1809/crudapp
      ports:
            - containerPort: 32778
      imagePullSecrets:
        - name: regcred
