apiVersion: apps/v1
kind: Deployment
metadata:
  name: umeshcrudapp-deployment
  labels:
    app: umeshcrudapp
spec:
  replicas: 3 # Increased to 3 to effectively demonstrate a rolling change
  # --- ROLLING UPDATE STRATEGY CONFIGURATION ---
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Spins up exactly 1 extra pod during update
      maxUnavailable: 0  # Guarantees zero downtime by keeping old pods alive
  # ---------------------------------------------
  selector:
    matchLabels:
      app: umeshcrudapp
  template:
    metadata:
      labels:
        app: umeshcrudapp
  spec:
    containers:
    - name: umeshcrudapp-container
      image: k8spraticeacr.azurecr.io/umeshcrudapp:latest
      ports:
      - containerPort: 32778