apiVersion: v1
kind: Service
metadata:
  labels:
    app: coffeshop
spec:
  containers:
    - name: crudapplication
      image: docker.io/umesh1809/newapp1:latest
      ports:
        - containerPort: 32777
