apiVersion: v1
kind: Service
metadata:
  name: crudapp-service
spec:
  type: NodePort
  selector:
    app: crudapp
  ports:
    - port: 80
      targetPort: 32778
      nodePort: 30007
  imagePullSecrets:
    - name: regcred