apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeshop
  template:
    metadata:
      labels:
        app: coffeshop
    spec:
      containers:
        - name: crudapplication
          image: docker.io/umesh1809/feapp:v2
          ports:
            - containerPort: 32778
      imagePullSecrets:
        - name: regcred
